// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/analyzer.proto

package analyzerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_api_proto_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_api_proto_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *AnalyzeResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Issue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Severity       string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Recommendation string                 `protobuf:"bytes,3,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Path           string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_api_proto_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_api_proto_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Issue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Issue) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *Issue) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_api_proto_analyzer_proto protoreflect.FileDescriptor

const file_api_proto_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/analyzer.proto\x12\banalyzer\"(\n" +
	"\x0eAnalyzeRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"P\n" +
	"\x0fAnalyzeResponse\x12'\n" +
	"\x06issues\x18\x01 \x03(\v2\x0f.analyzer.IssueR\x06issues\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x81\x01\n" +
	"\x05Issue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12&\n" +
	"\x0erecommendation\x18\x03 \x01(\tR\x0erecommendation\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path2Q\n" +
	"\x0fAnalyzerService\x12>\n" +
	"\aAnalyze\x12\x18.analyzer.AnalyzeRequest\x1a\x19.analyzer.AnalyzeResponseB\x18Z\x16./api/proto/analyzerpbb\x06proto3"

var (
	file_api_proto_analyzer_proto_rawDescOnce sync.Once
	file_api_proto_analyzer_proto_rawDescData []byte
)

func file_api_proto_analyzer_proto_rawDescGZIP() []byte {
	file_api_proto_analyzer_proto_rawDescOnce.Do(func() {
		file_api_proto_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_analyzer_proto_rawDesc), len(file_api_proto_analyzer_proto_rawDesc)))
	})
	return file_api_proto_analyzer_proto_rawDescData
}

var file_api_proto_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_analyzer_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: analyzer.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 1: analyzer.AnalyzeResponse
	(*Issue)(nil),           // 2: analyzer.Issue
}
var file_api_proto_analyzer_proto_depIdxs = []int32{
	2, // 0: analyzer.AnalyzeResponse.issues:type_name -> analyzer.Issue
	0, // 1: analyzer.AnalyzerService.Analyze:input_type -> analyzer.AnalyzeRequest
	1, // 2: analyzer.AnalyzerService.Analyze:output_type -> analyzer.AnalyzeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_analyzer_proto_init() }
func file_api_proto_analyzer_proto_init() {
	if File_api_proto_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_analyzer_proto_rawDesc), len(file_api_proto_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analyzer_proto_goTypes,
		DependencyIndexes: file_api_proto_analyzer_proto_depIdxs,
		MessageInfos:      file_api_proto_analyzer_proto_msgTypes,
	}.Build()
	File_api_proto_analyzer_proto = out.File
	file_api_proto_analyzer_proto_goTypes = nil
	file_api_proto_analyzer_proto_depIdxs = nil
}
